id: P42028603
initial_creation_type: input
source_metadata:
  title: Jigme Tenpé Wangchuk Series
  language: en
  description: 'Texts by and about the Sixth Gungthang Lama, Jigme Tenpé Wangchuk
    (''jigs med bstan pa''i dbang phyug, 1926–2000):'
  volume:
    ac2dafc167a14d2b96ce996b7fe22ffd:
      title: Aspiration for Electric Lamps
      parent: Aspiration Prayers
created_at: '2022-03-01T00:08:17.082236'
last_modified_at: '2022-03-01T00:08:17.082242'
